version: '3.8'
services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-full
    container_name: kotaemon
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    restart: always